### ISSUE TITLE
Sebilis (possibly more Kunark) textures error out

### ISSUE THREAD

**Issue by Impact1983** [LanternEQ/LanternExtractor#15]
G:\LanternExtractor\LanternExtractor\bin\Release>lanternextractor sebilis

Unhandled Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Stream stream)
   at LanternExtractor.Infrastructure.ImageWriter.WriteImage(Stream bytes, String filePath, String fileName, ShaderType type) in G:\LanternExtractor\LanternExtractor\Infrastructure\ImageWriter.cs:line 35
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteImage(Int32 index, ShaderType type, String folderName) in G:\LanternExtractor\LanternExtractor\EQ\Pfs\PfsArchive.cs:line 365
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteAllFiles(Dictionary`2 textureTypes, String folderName, Boolean onlyTextures) in G:\LanternExtractor\LanternExtractor\EQ\Pfs\PfsArchive.cs:line 263
   at LanternExtractor.LanternExtractor.ExtractZoneFile(String shortName) in G:\LanternExtractor\LanternExtractor\LanternExtractor.cs:line 176
   at LanternExtractor.LanternExtractor.ExtractZone(String shortName) in G:\LanternExtractor\LanternExtractor\LanternExtractor.cs:line 126
   at LanternExtractor.LanternExtractor.Main(String[] args) in G:\LanternExtractor\LanternExtractor\LanternExtractor.cs:line 56

System.ArgumentException
  HResult=0x80070057
  Message=Parameter is not valid.
  Source=System.Drawing
  StackTrace:
   at System.Drawing.Bitmap..ctor(Stream stream)
   at LanternExtractor.Infrastructure.ImageWriter.WriteImage(Stream bytes, String filePath, String fileName, ShaderType type)
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteImage(Int32 index, ShaderType type, String folderName)
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteAllFiles(Dictionary`2 textureTypes, String folderName, Boolean onlyTextures)
   at LanternExtractor.LanternExtractor.ExtractZoneFile(String shortName)
   at LanternExtractor.LanternExtractor.ExtractZone(String shortName)
   at LanternExtractor.LanternExtractor.Main(String[] args)

  This exception was originally thrown at this call stack:
    [External Code]

**Comment by danwilkins** [comment]
Please use new `0.1.5` branch and let us know if problem persists.
