### ISSUE TITLE
Illligal characters in path

### ISSUE THREAD

**Issue by arrissing** [LanternEQ/LanternExtractor#32]
Hi Team

having a strange issue with extracting, im getting the following error about 50% of the way through.
I have tried on EQ Titanium, Faydwer and Current.

any help appreciated.

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at LanternExtractor.EQ.Wld.Exporters.TextAssetWriter.WriteAssetToFile(String fileName)
   at LanternExtractor.EQ.Wld.Exporters.MeshExporter.ExportMeshes(WldFile wldFile, Settings settings, ILogger logger)
   at LanternExtractor.EQ.Wld.WldFile.ExportMeshes()
   at LanternExtractor.EQ.Wld.WldFile.ExportData()
   at LanternExtractor.EQ.Wld.WldFileEquipment.ExportData()
   at LanternExtractor.EQ.Wld.WldFile.Initialize(String rootFolder, Boolean exportData)
   at LanternExtractor.EQ.ArchiveExtractor.InitializeWldAndWriteTextures(WldFile wldFile, String rootFolder, String texturePath, PfsArchive s3dArchive, Settings settings, ILogger logger)
   at LanternExtractor.EQ.ArchiveExtractor.ExtractArchiveEquipment(String rootFolder, ILogger logger, Settings settings, PfsFile wldFileInArchive, String shortName, PfsArchive s3dArchive)
   at LanternExtractor.EQ.ArchiveExtractor.Extract(String path, String rootFolder, ILogger logger, Settings settings)
   at LanternExtractor.LanternExtractor.Main(String[] args)

**Comment by danwilkins** [comment]
@arrissing do you know the specific file it's failing on?
