### ISSUE TITLE
Branch 1.0: Unhandled Exception: Parameter is not valid error on export

### ISSUE THREAD

**Issue by azereki** [LanternEQ/LanternExtractor#5]
**Settings installation path:**
```
# EverQuest Installation Path
EverQuestDirectory = C:\Program Files (x86)\Steam\steamapps\common\Everquest F2P
```
**Command Prompt output:**
```
C:\LanternExtractor>lanternextractor neriaka

Unhandled Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Stream stream)
   at LanternExtractor.Infrastructure.ImageWriter.WriteImage(Stream bytes, String filePath, String fileName, ShaderType type)
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteImage(Int32 index, ShaderType type, String folderName)
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteAllFiles(Dictionary`2 textureTypes, String folderName, Boolean onlyTextures)
   at LanternExtractor.LanternExtractor.ExtractZoneFile(String shortName)
   at LanternExtractor.LanternExtractor.ExtractZone(String shortName)
   at LanternExtractor.LanternExtractor.Main(String[] args)

C:\LanternExtractor>
```
**Output files:**
**![lanternEQ-NeriakaOutput](https://user-images.githubusercontent.com/11672598/81487248-cfff4800-920f-11ea-89ef-19cbd8abbb72.png)**

**Comment by danwilkins** [comment]
This is caused by trying to extract newer zones. Some of the files are named as bitmaps but are actually .dds files. Will look into this in the future.
